USE T_OPFlix;

INSERT INTO CLIENTEADMINISTRADOR (IDCLIENTEADMINISTRADOR ,NOME) VALUES (1, 'ADM')
INSERT INTO CLIENTEADMINISTRADOR (IDCLIENTEADMINISTRADOR ,NOME) VALUES (2, 'Cliente')

INSERT INTO USUARIOS (IDUSUARIO ,NOME, EMAIL, SENHA, IDCLIENTEADMINISTRADOR) VALUES ('1' ,'Erik','erik@gmail.com',123456,1);
INSERT INTO USUARIOS (IDUSUARIO ,NOME, EMAIL, SENHA, IDCLIENTEADMINISTRADOR) VALUES ('2' ,'Cassiana','cassiana@gmail.com',123456,1);
INSERT INTO USUARIOS (IDUSUARIO ,NOME, EMAIL, SENHA, IDCLIENTEADMINISTRADOR) VALUES ('3' ,'Helena','Helena@gmail.com',123456,2);
INSERT INTO USUARIOS (IDUSUARIO ,NOME, EMAIL, SENHA, IDCLIENTEADMINISTRADOR) VALUES ('4' ,'Roberto','rob@gmail.com',3110,2);

SELECT * FROM USUARIOS;

INSERT INTO CATEGORIA (IDCATEGORIA, NOME) VALUES ('1','Comédia')
INSERT INTO CATEGORIA (IDCATEGORIA, NOME) VALUES ('2','Drama')
INSERT INTO CATEGORIA (IDCATEGORIA, NOME) VALUES ('3','Ficção Científica')
INSERT INTO CATEGORIA (IDCATEGORIA, NOME) VALUES ('4','Medico')
INSERT INTO CATEGORIA (IDCATEGORIA, NOME) VALUES ('5','Terror')

SELECT * FROM CATEGORIA ORDER BY IDCATEGORIA ASC;

INSERT INTO FILMESSERIES (NOME, DATALANÇAMENTO) VALUES ('Annabelle 3: De Volta Para Casa','2019-06-26')
INSERT INTO FILMESSERIES (NOME, DATALANÇAMENTO) VALUES ('Todo Mundo Odeia O Chris','2005-09-22')
INSERT INTO FILMESSERIES (NOME, DATALANÇAMENTO) VALUES ('Vingadores Guerra Infinita','2018-04-26')
INSERT INTO FILMESSERIES (NOME, DATALANÇAMENTO) VALUES ('Titanic','1998-01-16')
INSERT INTO FILMESSERIES (NOME, DATALANÇAMENTO) VALUES ('Grey`s Anatomy','2005-03-27')

SELECT * FROM FILMESSERIES;

INSERT INTO PLATAFORMAS (NOME) VALUES ('Google play Filmes')
INSERT INTO PLATAFORMAS (NOME) VALUES ('Netflix')
INSERT INTO PLATAFORMAS (NOME) VALUES ('Amazon')
INSERT INTO PLATAFORMAS (NOME) VALUES ('Vizer')

SELECT * FROM PLATAFORMAS ORDER BY IDPLATAFORMA ASC;

INSERT INTO TIPOCATEGORIA (IDFILMESSERIES, IDCATEGORIA) VALUES (1,3)
INSERT INTO TIPOCATEGORIA (IDFILMESSERIES, IDCATEGORIA) VALUES (2,1)
INSERT INTO TIPOCATEGORIA (IDFILMESSERIES, IDCATEGORIA) VALUES (3,4)
INSERT INTO TIPOCATEGORIA (IDFILMESSERIES, IDCATEGORIA) VALUES (4,5)
INSERT INTO TIPOCATEGORIA (IDFILMESSERIES, IDCATEGORIA) VALUES (5,2)

SELECT * FROM TIPOCATEGORIA;

