SELECT * FROM USUARIOS;
SELECT * FROM CATEGORIA;
SELECT * FROM FILMESSERIES;
SELECT * FROM PLATAFORMAS;
SELECT * FROM TIPOCATEGORIA;

SELECT * FROM USUARIOS;

SELECT * FROM CATEGORIA ORDER BY IDCATEGORIA ASC;

SELECT * FROM FILMESSERIES;

SELECT * FROM PLATAFORMAS ORDER BY IDPLATAFORMA ASC;

SELECT * FROM TIPOCATEGORIA;
